version: '3'
services:
  mongo:
    image: mongo:4.0
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    restart: always
  redis:
    image: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: always
  mosquitto:
    build: 
      context: services/mosquitto
      args:
        MQTT_BROKER_USERNAME: "${MQTT_BROKER_USERNAME}"
        MQTT_BROKER_PASSWORD: "${MQTT_BROKER_PASSWORD}"
    ports:
      - "${MQTT_BROKER_PORT}:${MQTT_BROKER_PORT}"
    restart: always